name: julianafranchin
favicon: null
layout_spectrum: 0.49522
typography_spectrum: 0.57917
title: Juliana Franchin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5fc7ce'
    - '#9fb7dd'
    - '#70a5cf'
    - '#d1ecee'
  brandStrength: 0
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
